### ISSUE TITLE
tests fail on 64bit Arch Linux

### ISSUE THREAD

**Issue by pigfrown** [PIVX-Project/PIVX#186]
Building on a 64 Bit Arch Linux LXC container, kernel 4.10.13-1.
Built dependencies with ```make NO_QT=1``` in ```pivx/depends``` to get around #149
configured with ``` ./configure --prefix=/home/pivx/pivx/depends/x86_64-pc-linux-gnu```

ran make check and got two fails, src/test_suite.log is as follows:
```
# TOTAL: 2
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/test_pivx
====================

Running 135 test cases...
test/alert_tests.cpp(123): error: in "Alert_tests/AlertApplies": check alert.CheckSignature() has failed
test/alert_tests.cpp(123): error: in "Alert_tests/AlertApplies": check alert.CheckSignature() has failed
test/alert_tests.cpp(123): error: in "Alert_tests/AlertApplies": check alert.CheckSignature() has failed
test/alert_tests.cpp(123): error: in "Alert_tests/AlertApplies": check alert.CheckSignature() has failed
test/alert_tests.cpp(123): error: in "Alert_tests/AlertApplies": check alert.CheckSignature() has failed
test/alert_tests.cpp(123): error: in "Alert_tests/AlertApplies": check alert.CheckSignature() has failed
test/alert_tests.cpp(123): error: in "Alert_tests/AlertApplies": check alert.CheckSignature() has failed
test/alert_tests.cpp(123): error: in "Alert_tests/AlertApplies": check alert.CheckSignature() has failed
test/alert_tests.cpp(129): error: in "Alert_tests/AlertApplies": check alerts[0].AppliesTo(1, "") has failed
test/alert_tests.cpp(130): error: in "Alert_tests/AlertApplies": check alerts[0].AppliesTo(999001, "") has failed
test/alert_tests.cpp(131): error: in "Alert_tests/AlertApplies": check alerts[0].AppliesTo(1, "/Satoshi:11.11.11/") has failed
test/alert_tests.cpp(133): error: in "Alert_tests/AlertApplies": check alerts[1].AppliesTo(1, "/Satoshi:0.1.0/") has failed
test/alert_tests.cpp(134): error: in "Alert_tests/AlertApplies": check alerts[1].AppliesTo(999001, "/Satoshi:0.1.0/") has failed
test/alert_tests.cpp(136): error: in "Alert_tests/AlertApplies": check alerts[2].AppliesTo(1, "/Satoshi:0.1.0/") has failed
test/alert_tests.cpp(137): error: in "Alert_tests/AlertApplies": check alerts[2].AppliesTo(1, "/Satoshi:0.2.0/") has failed
test/alert_tests.cpp(170): error: in "Alert_tests/AlertNotify": check r.size() == 4u has failed [0 != 4]
unknown location(0): fatal error: in "Alert_tests/AlertNotify": memory access violation at address: 0x00000008: no mapping at fault address
test/alert_tests.cpp(176): last checkpoint

*** 17 failures are detected in the test module "Pivx Test Suite"
FAIL test/test_pivx (exit status: 201)

FAIL: test/bitcoin-util-test.py
===============================

Traceback (most recent call last):
  File "./test/bitcoin-util-test.py", line 12, in <module>
    "bitcoin-util-test.json",buildenv)
  File "/home/pivx/pivx/src/test/bctest.py", line 51, in bctester
    bctest(testDir, testObj, buildenv.exeext)
  File "/home/pivx/pivx/src/test/bctest.py", line 27, in bctest
    proc = subprocess.Popen(execrun, stdin=stdinCfg, stdout=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '././bitcoin-tx'
FAIL test/bitcoin-util-test.py (exit status: 1)```

**Comment by Fuzzbawls** [comment]
The unit test suite is non-passing for all OS distributions and types at the moment. I've been working on getting them ported and fixed for the PIVX chain this past week and I'm nearing completion though.

**Comment by Fuzzbawls** [comment]
See #191 for fixed tests

**Comment by Fuzzbawls** [comment]
Closing now that #191 has been merged. If you have further problems with `make check` or the unit test suite open a new issue.
