### ISSUE TITLE
pivxd segfault on FreeBSD

### ISSUE THREAD

**Issue by clinta** [PIVX-Project/PIVX#82]
After staking for about 20 hours, pivxd died with signal 11.

The backtrace from the core dump is below:

```
#0  0x0000000000ca31f9 in CMasternodePayments::CleanPaymentList (this=0x131d028) at masternode-payments.cpp:626

#1  0x0000000000beef69 in ThreadCheckObfuScationPool () at obfuscation.cpp:2270
#2  0x000000000054c698 in boost::_bi::list0::operator()<void (*)(), boost::_bi::list0> () at bind.hpp:198
#3  0x000000000054c638 in boost::_bi::bind_t<void, void (*)(), boost::_bi::list0>::operator() () at bind.hpp:1294
#4  0x000000000054c5cc in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(), boost::_bi::list0> >::run () at thread.hpp:116
#5  0x0000000801b70e94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.63.0
#6  0x00000008032a6b55 in pthread_create () from /lib/libthr.so.3
#7  0x0000000000000000 in ?? ()
(gdb) 
#0  0x0000000000ca31f9 in CMasternodePayments::CleanPaymentList (this=0x131d028) at masternode-payments.cpp:626
#1  0x0000000000beef69 in ThreadCheckObfuScationPool () at obfuscation.cpp:2270
#2  0x000000000054c698 in boost::_bi::list0::operator()<void (*)(), boost::_bi::list0> () at bind.hpp:198
#3  0x000000000054c638 in boost::_bi::bind_t<void, void (*)(), boost::_bi::list0>::operator() () at bind.hpp:1294
#4  0x000000000054c5cc in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(), boost::_bi::list0> >::run () at thread.hpp:116
#5  0x0000000801b70e94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.63.0
#6  0x00000008032a6b55 in pthread_create () from /lib/libthr.so.3
#7  0x0000000000000000 in ?? ()
```

This binary was built from  v2.1.6 (25bad68) with the patch in #73 applied.

**Comment by clinta** [comment]
Looks like this might be fixed in dash [here](https://github.com/dashpay/dash/pull/978) and these changes just need to be brought in.

**Comment by clinta** [comment]
I'm building with that commit cherry-picked and will report back.

**Comment by Fuzzbawls** [comment]
Noted, thanks.

Leaving open pending further results or until a PR addressing this can be properly formulated.

**Comment by clinta** [comment]
Been running stable for over 30 hours now, which is longer than I've ever been able to keep it running before. PR #85 to merge this fix has been submitted.

**Comment by clinta** [comment]
Second update. Still running stable, up for 88 hours.
