### ISSUE TITLE
Error processing block 1679090

### ISSUE THREAD

**Issue by PeterL73** [PIVX-Project/PIVX#828]
While processing blocks PIVX (both d and qt) crashes with *** stack smashing detected *** on  block 1679090 

### What version of PIVX Core are you using?
v3.1.99.0-37a06eaa9
v3.1.99.0-ed0dd2a20
v3.1.99.0-95ec0763c

### Machine specs:
- OS:Ubuntu 18.04

### Any extra information that might be useful in the debugging process.
debug.log (last lines)
```
2019-03-04 20:26:02 ProcessNewBlock : block contains 1 zPIV mints and 0 zPIV spends
2019-03-04 20:26:02 UpdateTip: new best=ae90e3bf0b9d4b065642effe4e3ec2db174f16b0b076c942ddd504c696ac520c  height=1679089 version=4  log2_work=69.59283  tx=4018151  date=2019-03-02 01:39:34 progress=0.997252  cache=609
2019-03-04 20:26:02 ProcessNewBlock : ACCEPTED Block 1679089 in 105 milliseconds with size=946
```
gdb backtrace (running v3.1.99.0-37a06eaa9)
``` gdb
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff58e4801 in __GI_abort () at abort.c:79
#2  0x00007ffff592d897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff5a5a988 "*** %s ***: %s terminated\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff59d8cd1 in __GI___fortify_fail_abort (need_backtrace=need_backtrace@entry=false, msg=msg@entry=0x7ffff5a5a966 "stack smashing detected") at fortify_fail.c:33
#4  0x00007ffff59d8c92 in __stack_chk_fail () at stack_chk_fail.c:29
#5  0x0000555555988ba8 in libzerocoin::ExtractVersionFromSerial (bnSerial=...) at libzerocoin/Coin.cpp:262
#6  0x4d6e79e5d48eda6d in ?? ()
#7  0xb22e509c0adaf9cf in ?? ()
#8  0x813f595cec5e9413 in ?? ()
#9  0x036a37cfc6c08eea in ?? ()
#10 0xfb806ed72efed122 in ?? ()
#11 0x00005555561228c8 in CChainParams::Zerocoin_Params(bool) const::ZCParamsDec ()
#12 0x00007fffd091f598 in ?? ()
#13 0x00007fffd091f588 in ?? ()
#14 0x0000000000004fda in ?? ()
#15 0xb4168ea52f5736ff in ?? ()
#16 0x00007fffd091f310 in ?? ()
#17 0x00007fffd09200f0 in ?? ()
#18 0x35f5dd83d2484900 in ?? ()
#19 0x00007fffb99ffff0 in ?? ()
#20 0x00007fffb9a04fca in ?? ()
#21 0x00007fffb9a04fca in ?? ()
#22 0x0000000100000000 in ?? ()
#23 0x0000000000011502 in ?? ()
#24 0x000000000000007c in ?? ()
#25 0x00007fffb99f4364 in ?? ()
#26 0x0000000000000000 in ?? ()
```
Have been testing different commits. It seems v3.1.99.0-c93bf2b61 is working correct while v3.1.99.0-95ec0763c doesn't work, so i think this problem was introduced in commit: 95ec0763cf49ab5f935efe82b9845c83fa010d99

**Comment by furszy** [comment]
Working on it, issue arises when the wallet uses gmp instead of openssl.

Meanwhile, you can compile the wallet with openssl and it will work fine.
