### ISSUE TITLE
Segfault when recalculating zPIV spends/supply with GUI Wallet

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#859]
### Describe the issue
When doing a fresh sync with the GUI wallet, the dialog window showing the progress of recalculating the zPIV spends or the zPIV supply is double closed, which causes a segfault.

#### If so, please list the steps to reproduce below:
1. Open and sync GUI wallet from a block prior to zPIV activation
2. Continue sync to the point that zPIV spends/supply are recalculated (908000)

### Expected behavior
The progress dialog should open, fill, and close gracefully

### Actual behavior
The progress dialog opens, fills, then gets closed twice; second attempt to close causes segfault

### What version of PIVX Core are you using?
v3.2.0 Release

### Machine specs:
- OS: N/A
- CPU: N/A
- RAM: N/A
- Disk size: N/A
- Disk Type (HD/SDD): N/A

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

GDB Backtrace:
```
Thread 1 "pivx-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff64ea32f in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) backtrace
#0  0x00007ffff64ea32f in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff6e1b2bd in QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00005555555f352e in BitcoinGUI::showProgress (this=0x5555565bc500, title=..., nProgress=<optimized out>) at qt/bitcoingui.cpp:1342
#3  0x000055555567cb2f in BitcoinGUI::qt_static_metacall (_o=0x5555565bc500, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at qt/moc_bitcoingui.cpp:266
#4  0x00007ffff6518d2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x000055555567df56 in ClientModel::showProgress (this=<optimized out>, _t1=..., _t2=100) at qt/moc_clientmodel.cpp:267
#6  0x00007ffff6519c01 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff6ddd05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff6de2516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff64ea38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff64ec786 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff65403c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff31e7197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff31e73f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
```

**Comment by Nakamoto-san** [comment]
v3.2.1 eta?

**Comment by Mrostgaard** [comment]
I'm still getting this exact error in v3.2.2 is there any woraround for it? I've tried the fresh install like 3 times..
